### PR TITLE
Updated site name

### PR DESCRIPTION
**Pull request by ghost**
Changed the site name. I'm not entirely sure if I did this correctly, since I've never used react.

### CODE REVIEW

**Comment by quentinguidee** [comment]
I think you changed the sitemap.xml, a file which help the google algorithm; not the site itself...

**Comment by ghost** [comment]
oops

**Comment by ghost** [comment]
I didn't see anything to edit with the old site name when I did a recursive grep.

**Comment by fmlatghor** [comment]
There's nothing wrong so I'm just going to leave this alone.

**Pull request closed without merging**
